services:
  yolo-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: yolo-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro # pesos somente-leitura
      - ./output:/app/output # resultados gravados aqui
      - ./images:/app/images:ro # imagens de teste
    environment:
      - MODEL_NAME=yolov8n.pt
    networks:
      - yolo-net
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3

  yolo-client:
    image: ghcr.io/sarahmendes-ufca/yolo-edge-api/yoloapi:latest
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: yolo-client
    volumes:
      - ./images:/client/images:ro
      - ./output:/client/output
    environment:
      - API_URL=http://yolo-api:8000
    networks:
      - yolo-net
    depends_on:
      yolo-api:
        condition: service_healthy

  yolo-stream:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: yolo-stream
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - ./stream:/app/stream
      - ./models:/app/models:ro
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - MODEL_NAME=yolov8n.pt
    command: >
      python3 stream/mjpeg_server.py
      --device 0
      --infer-every 3
      --infer-size 320
      --port 5000
    restart: unless-stopped
    depends_on:
      yolo-api:
        condition: service_healthy
    networks:
      - yolo-net

networks:
  yolo-net:
    driver: bridge
